# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image_id',
        ),
        migrations.AddField(
            model_name='slider',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='slidethumb'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.ImageField(upload_to='thumb'),
        ),
    ]
