# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190113_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Images'),
        ),
    ]
