# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20190113_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='images_i',
            new_name='images_id',
        ),
    ]
