# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20190113_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(default=1, to='blogs.Tag'),
        ),
    ]
