# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20190113_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.Images'),
        ),
    ]
