# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20190113_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'view_blog_user',
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
