# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20190113_1513'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users_view',
            table='view_users',
        ),
    ]
